@urlEP=http://localhost:8000/api/v1/users

### Get request
GET {{urlEP}}?id=8&fName=Gary&lName=Tm


### Post user request
POST {{urlEP}}
Content-Type: application/json

 {
            "id": "5",
            "fName": "Savcm",
            "lName": "Smdith"
        }
### curl -X POST "http://localhost:8000" -H "Content-Type: application/json" -d "{"id": "5","fName": "Savcm",lName": "Smdith"}"

### Update user request
PUT  {{urlEP}}
Content-Type: application/json
Authorization: 23DSFSAFS44;

{
    "id":"2",
    "fName":"Mary"
}


### Delete user request
DELETE  http://localhost:8000/333
